### ISSUE TITLE
web3 requires "0x" appended to hashes.

### ISSUE THREAD

**Issue by simondlr** [ConsenSys/reflux-tx#1]
Not entirely sure where to add this check. It caused issues when creating new blocks. Need to add a check somewhere and then append it to the hash if it is not there. Not sure where the best place is for this.

**Comment by kumavis** [comment]
`0x` prefix is the gift that keeps on giving

**Comment by jeffscottward** [comment]
Hehehe :)
Can we post to Reddit as a call to the community to standardize on 0x?

**Comment by ckeenan** [comment]
Hey @simondlr do you know the exact place that '0x' was causing your issue? I can enforce a standard on tx hashes that are `add`-ed, but am not sure if that was your problem. What did you do to resolve it?

**Comment by simondlr** [comment]
See my fork and the most recent commit (replying from my phone otherwise would've pasted here).

I'm not sure if it will give issues at other places, but that's where I encountered it.

**Comment by ckeenan** [comment]
@simondlr ah missed that, thanks.
Hey I just pushed some changes that should fix this. Can you test it out and lmk?

**Comment by simondlr** [comment]
@ckeenan doesn't work. I commented on the commit. Seems like the dist file didn't properly compile from the source files?

**Comment by ckeenan** [comment]
@simondlr good catch, thanks. Really should have tests for the dist version... So I guess I must have committed an old build? Could have sworn I rebuilt after the latest commit. Anyways, I updated the builds; should work now.

**Comment by simondlr** [comment]
I seem to be getting a new error now. When I try to create a contract, I get this:

`Uncaught TypeError: cb is not a function`

Happening here: https://github.com/ConsenSys/reflux-tx/blob/d72eb9fd0c40dba4234a799d60a440020abdbba1/src/Store.js#L650.

I assume maybe it has to do with newHashes not being the right kind (with the hash changes)?

**Comment by ckeenan** [comment]
Yeah that cb should check if its a function at least. but something is throwing an error. @simondlr what version of web3 & geth?

**Comment by ckeenan** [comment]
turns out to be a problem specifically when connecting to ethersim which expecting the 0x, I can't reproduce this with geth
@simondlr I added the change to the eth_calls that needed it and tested it works with your app
can you verify that too pls?

**Comment by simondlr** [comment]
Whoop. Thanks @ckeenan! It works perfectly now with 0.1.5. :clap:
